// ─────────────────────────────────────────────────────────────────────────────
// Cancer Survivor Conversation Simulator — Notices page
//
// Johnson Educational & Teaching Services · ABN 15 440 542 589
// Destination: client/src/components/Notices.jsx
//
// Plugs into the existing "About this prototype" modal in App.jsx as a second
// tab or a linked section. The attribution line already on the landing page
// stays as it is — this is the destination it should link to.
//
// The dependency list is FETCHED, not hard-coded, so it cannot drift from the
// generated THIRD-PARTY-NOTICES.txt. Serve that file as a static asset.
// ─────────────────────────────────────────────────────────────────────────────

import { useEffect, useState } from 'react';

export default function Notices() {
  const [notices, setNotices] = useState(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    fetch('/THIRD-PARTY-NOTICES.txt')
      .then(r => (r.ok ? r.text() : Promise.reject()))
      .then(setNotices)
      .catch(() => setFailed(true));
  }, []);

  return (
    <section className="notices">
      <h2>Notices and attribution</h2>

      <h3>About this tool</h3>
      <p>
        Built by Johnson Educational &amp; Teaching Services, an education-support
        provider. JETS is not an accredited institution and this tool confers no
        qualification.
      </p>
      <p>
        It is a training aid. It is not a clinical or diagnostic tool, and nothing
        in it should be used to guide the care of a real patient. Every patient
        here is fictional.
      </p>

      <h3>Where the numbers come from</h3>
      <p>
        Test characteristics in the surveillance-result scenarios are drawn from
        published research and cited in the debrief. Pre-test probabilities and
        all likelihood ratios in the confidence-allocation exercise are{' '}
        <strong>illustrative</strong> — chosen so the reasoning works, not
        measured from a population. They are labelled as such wherever they
        appear. Do not carry any figure from this tool into practice.
      </p>

      <h3>Teaching frameworks</h3>
      <p>
        The reasoning structure, debrief format and rubric descriptors used here
        are original work, built on concepts in general use and on publicly
        released material. No licensed or proprietary assessment instrument is
        reproduced or adapted.
      </p>

      <h3>Artificial intelligence</h3>
      <p>
        Patient responses and written feedback are generated by a large language
        model. Scoring in the confidence-allocation exercise is computed
        arithmetically and is not produced by the model. Feedback is formative and
        is not a substitute for assessment by a qualified educator.
      </p>

      <h3>Open-source components</h3>
      {notices && <pre className="notices__licences">{notices}</pre>}
      {failed && (
        <p>
          Attribution for open-source components is available on request from
          Johnson Educational &amp; Teaching Services.
        </p>
      )}
      {!notices && !failed && <p>Loading…</p>}

      <h3>Support</h3>
      <p>
        <strong>Nurse &amp; Midwife Support</strong> — 1800 667 877. Free,
        confidential, 24/7, open to nursing and midwifery students.<br />
        <strong>Lifeline</strong> — 13 11 14.<br />
        In an emergency, call 000.
      </p>

      <footer className="notices__footer">
        Johnson Educational &amp; Teaching Services · ABN 15 440 542 589 ·
        Byford WA 6122
      </footer>
    </section>
  );
}
